#Denne tester konseptet med at en klient kjoerer en "pulljobb" der denne fila blir hentet fra github og kjoert.
# Pull jobb
- hosts: localhost
  user: root
  tasks:

  #
  - name: Slette rpm-fila /tmp/t.rpm
    file: path=/etc/gitconfig state=touch
