#Denne tester konseptet med at en klient kjoerer en "pulljobb" der denne fila blir hentet fra github og kjoert.
# Pull jobb
- hosts: localhost
  user: root
  tasks:

  #
  - name: En enkel jobb som "toucher" en fil
    file: path=/etc/gitconfig state=touch
